name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test ./tests/unit/... -v

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Integration Tests
        run: |
          export CI=true
          go test ./tests/integration/... -v -timeout 60m
env:
  CI: "true"
